version: 2
jobs:
  build:
    parallelism: 2
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install --upgrade pip
            pip install pytest
      - run:
          name: run tests
          command: |
            pytest --junitxml=test-reports/junit.xml $(circleci tests glob tests/**/test_*.py | circleci tests split)
      - store_test_results:
          path: test-reports